on:
  push:
    branches-ignore:
      - 'ci-test'
    tags-ignore:
      - '**'
  pull_request:
  # schedule:
  #   - cron: '13 15 * * *'
  workflow_dispatch:
jobs:
  wheel_linux:
    strategy:
      fail-fast: false
      matrix:
        py:
          - arch: 'aarch64'
            build: 'cp39-manylinux_aarch64'
          - arch: 'i686'
            build: 'cp39-manylinux_i686'
          - arch: 'x86_64'
            build: 'cp39-manylinux_x86_64'

          - arch: 'aarch64'
            build: 'cp310-manylinux_aarch64'
          - arch: 'i686'
            build: 'cp310-manylinux_i686'
          - arch: 'x86_64'
            build: 'cp310-manylinux_x86_64'

          - arch: 'aarch64'
            build: 'cp311-manylinux_aarch64'
          - arch: 'i686'
            build: 'cp311-manylinux_i686'
          - arch: 'x86_64'
            build: 'cp311-manylinux_x86_64'

          - arch: 'aarch64'
            build: 'cp312-manylinux_aarch64'
          - arch: 'i686'
            build: 'cp312-manylinux_i686'
          - arch: 'x86_64'
            build: 'cp312-manylinux_x86_64'

          - arch: 'aarch64'
            build: 'cp313-manylinux_aarch64'
          - arch: 'i686'
            build: 'cp313-manylinux_i686'
          - arch: 'x86_64'
            build: 'cp313-manylinux_x86_64'
    runs-on: ubuntu-22.04
    env:
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
      CIBW_BEFORE_BUILD: 'ci/install-rust-linux.sh'
      CIBW_ARCHS: ${{ matrix.py.arch }}
      CIBW_BUILD: ${{ matrix.py.build }}
      CIBW_BUILD_VERBOSITY: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run cibuildwheel
        run: |
          if [ "${CIBW_ARCHS}" = "aarch64" ]; then
              sudo apt update
              sudo apt install -y qemu binfmt-support qemu-user-static
          fi

          python3 -m pip install --upgrade pip==24.3.1
          python3 -m pip install cibuildwheel==2.22.0
          python3 -m cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.py.build }}
          path: |
            wheelhouse

  wheel_macos:
    strategy:
      fail-fast: false
      matrix:
        py:
          - build: 'cp39-macosx_x86_64'
          - build: 'cp310-macosx_x86_64'
          - build: 'cp311-macosx_x86_64'
          - build: 'cp312-macosx_x86_64'
          - build: 'cp313-macosx_x86_64'
    runs-on: macos-14
    env:
      CIBW_BUILD: ${{ matrix.py.build }}
      CIBW_BUILD_VERBOSITY: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run cibuildwheel
        run: |
          python3 -m pip install --upgrade pip==24.3.1
          python3 -m pip install cibuildwheel==2.22.0
          python3 -m cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.py.build }}
          path: |
            wheelhouse

  wheel_windows:
    strategy:
      fail-fast: false
      matrix:
        py:
          - build: 'cp39-win_amd64'
          - build: 'cp310-win_amd64'
          - build: 'cp311-win_amd64'
          - build: 'cp312-win_amd64'
          - build: 'cp313-win_amd64'
    runs-on: windows-2022
    env:
      CIBW_BUILD_VERBOSITY: '1'
      CIBW_BUILD: ${{ matrix.py.build }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Run cibuildwheel
        run: |
          python -m pip install --upgrade pip==24.3.1
          python -m pip install cibuildwheel==2.22.0
          python -m cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.py.build }}
          path: |
            wheelhouse

  merge_artifacts:
    runs-on: ubuntu-22.04
    needs: [wheel_linux, wheel_windows, wheel_macos]
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          pattern: 'wheel-*'
          delete-merged: true

